### ISSUE TITLE
$all with $elemMatch does not work

### ISSUE THREAD

**Issue by jnicholl** [crcn/sift.js#108]
`sift({tags: {$all: [{$elemMatch: {a: 1}}]}}, [{tags: [{a: 1}]}, {tags: [{a: 1}, {b: 1}]}])` returns [], but running the same query against mongo returns both objects in the array.
Is this section (https://docs.mongodb.com/manual/reference/operator/query/all/#use-all-with-elemmatch) of $all/$elemMatch implemented?

**Comment by crcn** [comment]
Sorry for the delay - I just patched this up in `3.2.8`. Let me know if that fixes the issue on your end.

**Comment by jnicholl** [comment]
Works nicely now, thanks!
