### ISSUE TITLE
Check filter against single item?

### ISSUE THREAD

**Issue by jdarling** [crcn/sift.js#109]
I find that many times I'm using Sift to see if a record matches a pattern, would be nice if there were a way to just check a sifter against a single entity.

Currently I do something like:

```
const isFoo = sift({foo: 'bar'});
const matches = isFoo([someObject]).length > 0;
```

I understand that this isn't really in the scope of Sift, and maybe there is a better fit library out there for this, but thought I'd ask :D

**Comment by crcn** [comment]
What about something like this?

```javascript
const isFoo = sift({foo: 'bar'});
const matches = [someObject].filter(isFoo).length > 0;
```

**Comment by jdarling** [comment]
That would be another way of doing it.  It would be nice though to be able to do something like:

```js
const isFoo = sift({foo: 'bar'});
const matches = isFoo.matches(someObject); // maybe isFoo.exec(someObject)?
```

Similar to RegExp usage.

**Comment by jdarling** [comment]
When I rewrote sift in ES6 I realized that this already works with the current codebase:

```js
var sift = require('sift');
var isFoo = sift({foo: 'bar'});
isFoo({foo: 'bar'}); // -> true
 isFoo({bar: 'none'}); // -> false
```

Nice
