### ISSUE TITLE
ES6 rewrite/learning experience

### ISSUE THREAD

**Issue by jdarling** [crcn/sift.js#110]
This isn't a bug or a defect, but I got board today while working on my hack-a-thon project and rewrote sift.js in ES6.  Thought you might be interested https://github.com/anarchistengineering/mongo-bout

It isn't complete as it doesn't support custom operators as I want to add a class wrapper around everything that will contain custom settings.

Couldn't be a replacement for sift as it won't work in a browser ;)  Still its amazing how much bang you got for such little code.

**Comment by crcn** [comment]
`mongo-bout` looks great! I've thought about moving over to ES6, but there are still many users that rely on the ES5 version. Still, it's pretty cool to see what sift could look like in an upgraded version of JS -- thanks for sharing. 👍
