### ISSUE TITLE
$in does not work with ObjectId

### ISSUE THREAD

**Issue by igorlesnenko** [crcn/sift.js#116]
$in does not work with ObjectId

indexOf does not work with array of objects.

Possible solutions:

- Call to string on comparing object and check that result is different from [object Object] and if so compare by toString output. 
- Check that type of the object is ObjectId and compare by toString value
- Use some deep object comparison

**Comment by igorlesnenko** [comment]
```
$in: function(a, b) {
      if (b instanceof Array) {
        for (var i = b.length; i--;) {
          if (~a.indexOf(comparable(get(b, i)))) return true;
        }
      } else if (typeof b === 'object') {
        return !!~a.findIndex(el => {
          return el.toString() === b.toString()
        });
      } else {
        return !!~a.indexOf(comparable(b));
      }

      return false;
    },
```

**Comment by crcn** [comment]
Good idea! Added this functionality to `3.3.0` and published to NPM. 👍
