### ISSUE TITLE
$nin with undefined document and [null]

### ISSUE THREAD

**Issue by ixxqx** [crcn/sift.js#124]
1. Assume the following document in Mongo: {"a: 1, "b": 2, "c": {"d": 1, "e": 2}}.
2. Run the following query: db.collection.find({"c.x": {$nin: [1, 2, 3]}}) - it will return the original document as expected (since c.x is undefined, and is indeed not defined as either [1, 2, 3]).
3. Run the following query again: db.collection.find({"c.x": {$nin: [1, 2, 3, null]}}) - this time, the original document won't be returned. Since c.x is undefined, but "null" is appended to the parameters to $nin - our document won't be picked up by the query.
4. Sift doesn't implement this behaviour.

**Comment by ixxqx** [comment]
PR ready in https://github.com/crcn/sift.js/pull/123

**Comment by crcn** [comment]
Closing this ticket since #123 has been merged into `master`.
