### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by imarcano** [crcn/sift.js#139]
hi guys,

In mongoDB version 3.6 i can compare isoString dates (string typed) with $gte, $gt, $lt and $lte, but i cant do that with the current version of this project.

I should be able to filter objects doing this operation {field: {$gte: "2018-03-22T06:00:00Z"}} and it should filter accordingly since isoString dates allow you to do that.

**Comment by marcj** [comment]
AFAIK Mongo implicitly converts that to a Date before it starts the comparing, so I don't think that should be possible in Sift. You should use ` {field: {$gte: new Date("2018-03-22T06:00:00Z")}}` and you're golden.

**Comment by crcn** [comment]
> AFAIK Mongo implicitly converts that to a Date before it starts the comparison, so I don't think that should be possible in Sift. 

It _may_ be possible, but I'll need to spend some time figuring out a good way to do it. For now I think that using Date objects is probably the best approach. 

I added a section to the docs that explains behavior mismatches: https://github.com/crcn/sift.js#mongodb-behavior-differences.
