### ISSUE TITLE
$eq not matching if type is different

### ISSUE THREAD

**Issue by visualjerk** [crcn/sift.js#142]
I am not sure if this actually is a bug, but the docs for $eq state "Checks if query == value". That reads like $eq is using the equality operator for comparison. Therefore **'35'** (string) should be equal to **35** (number).

## Test

```javascript
var sift = require("sift")
sift({ height: {$eq: "35" }}, [{ height: 35 }]);
```
https://runkit.com/embed/bhuvsdz07m7k

## Expected result

An array with 1 entry

## Actual result

An empty array

**Comment by crcn** [comment]
Fixed the docs to reflect `===` for $eq.
