### ISSUE TITLE
$exists does not work properly (again)

### ISSUE THREAD

**Issue by syabro** [crcn/sift.js#146]
```javascript
var sift = require('sift');

const query = {
  'formData.kg': {
    '$exists': true,
  }
}


const data = [{
  'formData': {
    'kg': null,
  },
}]

console.log(sift(query, data)); // []
```
but according to docs it should not be filtered
https://docs.mongodb.com/manual/reference/operator/query/exists/#op._S_exists

![image](https://user-images.githubusercontent.com/29029/43777552-d67169aa-9a5b-11e8-937f-5c69456edc2c.png)

**Comment by crcn** [comment]
Doesn't look like I'm able to reproduce this issue -- this passes: https://github.com/crcn/sift.js/blob/master/test/operations-test.js#L140.

Would you mind checking if `8.0.0` fixes this issue?

**Comment by syabro** [comment]
@crcn 8.0.0 is not released. Should I check the latest develop?

**Comment by crcn** [comment]
`8.0.x` should be available under `beta` in NPM: https://www.npmjs.com/package/sift/v/8.0.1

**Comment by syabro** [comment]
@crcn we have `3.2.7` so I bet a lot has been changed :)
closing, will reopen if anything changes
