### ISSUE TITLE
Is $eq now required for simple cases?

### ISSUE THREAD

**Issue by dweldon** [crcn/sift.js#151]
In v7, this would return a non-empty array:

`[{ _id: 'v1', title: 'x' }].filter(sift({ _id: 'v1' }));`

In v8, it seems to only work with `$eq`:

`[{ _id: 'v1', title: 'x' }].filter(sift({ _id: { $eq: 'v1' } }));`

Is this the expected behavior?

**Comment by dweldon** [comment]
Oh I guess this is the intended behavior based on the "Queries now expect exact object shape" note in the change log. Unexpected, but I'll roll with it...

**Comment by sakulstra** [comment]
I also ust stubmled upon this...
we've been using sift mostly for mocking mongodb inside our test suite and batching queries via dataloader. This change makes sift incompatible with the mongodb driver effectively preventing us from updating :disappointed: 

Did someone face similar issues? And/Or already found a workaround?

**Comment by dweldon** [comment]
@sakulstra I'm also using it for batching/dataloader, and I find this change **extremely confusing** for our use case. Now every time I use a loader, I have to think "Oh wait this is going through `sift` so the query needs to be different."

Somewhat off topic, but as for your mongodb testing, you may want to consider using `mongodb-memory-server`, as I describe [here](https://stackoverflow.com/questions/13607732).
