### ISSUE TITLE
Breaking change to functionality in version 8

### ISSUE THREAD

**Issue by redgeoff** [crcn/sift.js#152]
I want to start off by saying that sift rocks and it has been super helpful in [mson](https://github.com/redgeoff/mson)!

Unfortunately, I recently tried to upgrade from v7 to v8 and there appears to be a massive breaking change, i.e. you now need to specify all the attributes in the query before anything is matched.

Take the example:

```
  console.log([{
    foo: 'bar',
    yar: 'nar'
  }].filter(
    sift({ foo: 'bar' })
  ));
```

with sift v7.0.1 and earlier, you get the output of `[ { foo: 'bar', yar: 'nar' } ]`, but with v8.0.1 and later, you get `[]`

To get an output of `[ { foo: 'bar', yar: 'nar' } ]` with v8.0.1, you need to include all the properties, e.g.

```
  console.log([{
    foo: 'bar',
    yar: 'nar'
  }].filter(
    sift({ foo: 'bar', yar: 'nar' })
  ));
```

Is this intentional or is this a bug?

**Comment by dweldon** [comment]
See the discussion for #151. I closed that issue because this change was intentional. I'm not thrilled with it either.

For your example query to work, you'd want to do: `.filter(sift({ foo: { $eq: 'bar' } }))`

**Comment by redgeoff** [comment]
Bummer! If this is intentional, I may need to fork v7 and start maintaining this fork.

**Comment by yoitsro** [comment]
I'm also facing this issue. I think there was some misinterpretation in #117 which has caused this issue.

Whatever the case, for me, explicitly using `$eq` doesn't even fix it for me.

This functionality is now _even more_ different from mongo.

**Comment by crcn** [comment]
Sorry everyone, this issue should be fixed now in `8.3.2`. 

> I think there was some misinterpretation in #117 which has caused this issue.

You're right, this was a misinterpretation 🙈. Object exactness should have only been applied to _properties_ of the top-most query.

**Comment by yoitsro** [comment]
I'll check out `8.3.2` now. Thank you for that and, generally, great work on this package 👏

**Comment by yoitsro** [comment]
I can confirm, with a quick run with `8.3.2` just now, that this is fixed. I would recommend that others try it out too though @redgeoff @dweldon.

Thank you for the speed of this fix @crcn!

**Comment by sakulstra** [comment]
8.3.2 resolved most issues we're facing, but there seem to be some leftovers

```
const array = [{ 'educations': [{ 'value': 'refa', 'unfinished': true }, { 'value': 'reno', 'unfinished': true }] }];
const query = {
  educations: {
    $elemMatch: {
      $or: [{
        value: 'refa',
        $or: [{ unfinished: true }]
      }, { 
        value: 'reno',
        $or: [{ unfinished: true }] }]
    }
  }
};
expect(array.filter(sift(query))).toHaveLength(1);
```
returns true on sift 7, but false on sift 8.3.2

**Comment by crcn** [comment]
> there seem to be some leftovers

Just pushed fixes to `8.3.3`, let me know if it works.

**Comment by redgeoff** [comment]
Thanks, Craig. Do you have these cases under test coverage?

**Comment by sakulstra** [comment]
seems like the latest update fixed all tests in our *not that huge* test suite :+1:!

**Comment by crcn** [comment]
> Thanks, Craig. Do you have these cases under test coverage?

You becha: https://github.com/crcn/sift.js/commit/db173503addd2a0bd2e8039f3bf74aff96de1bc2#diff-9079809255733a5a015a95f33de0b950R76

**Comment by crcn** [comment]
Gonna go ahead and close this ticket.

**Comment by crcn** [comment]
@redgeoff is the issue fixed for you? If so I'll go ahead and close this ticket.

**Comment by redgeoff** [comment]
Thanks, I’ll try and test this tonight

**Comment by dweldon** [comment]
I can confirm that after reverting my changes and upgrading to `8.3.3`, all of my tests pass. Thanks for the fix!

**Comment by redgeoff** [comment]
v8.3.3 appears to have fixed the problem. Thanks @crcn!
