### ISSUE TITLE
Allow to use only specific operators

### ISSUE THREAD

**Issue by stalniy** [crcn/sift.js#153]
It may be useful to expose all operators separately and allow users to create own instance of `sift` that supports only specific operators. 

benefits form this:
1. We can reduce bundle size on client (by using tree-shaking feature)
2. We can restrict users to use only  allowed operators (e.g., forbid usage of `$where`)
3. Potentially separation on operators and execution engine may allow to implement processing of async conditions easier

**Comment by crcn** [comment]
Do you mean to import operators separately into sift? E.g:

```javascript
import sift from 'sift';
import * as operators from 'sift/operators';

const filter = sift({ operators });
````

Additionally, operators could be separated out into individual files:

```javascript
import sift from 'sift';
import $where from 'sift/operators/$where';
import $in from 'sift/operators/$in';
import $eq from 'sift/operators/$in';

const filter = sift({ operators: {$where, $in, $eq} });
```

**Comment by stalniy** [comment]
Exactly!

**Comment by stalniy** [comment]
It’s enough to export each operator as a function, later webpack/roll up can shake out unused operators. 

In order to keep backward compatibility, I’d suggest to create a factory and operators separately then export default sift as an object created by the factory which uses all operators. Also export factory functions and all operators. 

```js
import { buildSift } from 'sift'
import * as operators from 'sift/operators'
```

**Comment by crcn** [comment]
@stalniy this should be fixed with the refactor. Docs are here: https://github.com/crcn/sift.js#custom-operations. Let me know what you think!

**Comment by stalniy** [comment]
Wow! Looks good! 

There are few missing peaces: 
1. You need to add `"sideEffects": false` in package.json if your TS modules are pure (i.e., doesn't modify anything outside functions/classes in module) - more info https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
2. You need to provide es5m build. This is a ES5 build with ES6 modules. 
    **Why ES5?** This will allow to use your module without additional transpilation by babel. You already have this
    **Why ES6 modules?** This will allow webpack and rollup to use static analyses of app/lib dependencies and remove unused functionality and reduce bundle size. It was the main purpose of this issue. 
    **How does this look?**
```js
// a.js
import { a, b } from './b'

export var c = a + b

// b.js
export var a = 1
export var b = 2
export function test() {
  //...
}
```

**Comment by crcn** [comment]
Thanks for the info, we're good! Here's the API:

```javascript
import {createQueryTester} from 'sift';
import {$in, $ne} from 'sift/operators';

const filter = createQueryTester({$ne: 5}, { operations: {$in, $ne} });
```

Documentation is here: https://github.com/crcn/sift.js#omitting-built-in-operations
