### ISSUE TITLE
Unexpected Results from sift

### ISSUE THREAD

**Issue by joshglenn** [crcn/sift.js#159]
Hello! 

I'm new to sift. But I am working with a project that uses it for validation. For some reason the project recently stopped validating email addresses properly. I tried to chase down the root of the problem by setting up a codesandbox to test it. 

I think the results that I am getting are incorrect. Am I making a mistake somewhere?
 
Here's my code:

```js
import sift from "sift";

let where = {
  $not: {
    value: {
      $regex: "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+.[A-Za-z]{2,4}$"
    }
  }
};
const whereProps = {
  value: "funky@example.com"
};

let sifted = sift(where, [whereProps]);
console.log(sifted);
console.log("results from sifted function", sifted());
console.log("sifted.length", sifted.length);
if (sifted.length > 0) {
  console.log("sifted yo");
}
```

Here's the results I see in the console:

```
function () {}
results from sifted function  true
sifted.length  3
sifted yo 
```

The function is returning true. True, as in, the string I am checking does not match the regex. But, use that regex with the regex match function, and it matches the regex. ([check out the codesandbox ](https://codesandbox.io/s/sift-email-validator-test-zev7k) and you'll see what I'm talking about).

Any idea what could be going wrong? Or am I doing something wrong?

**Comment by crcn** [comment]
`v8` introduces breaking API changes that can be found here: https://github.com/crcn/sift.js/blob/master/changelog.md#800.

Basically all you need to do is change `sift(where, [whereProps])` to `[whereProps].filter(sift(where))`. 🙂
