### ISSUE TITLE
create something similar for modifiers?

### ISSUE THREAD

**Issue by smeijer** [crcn/sift.js#162]
Any chance to have a similar package but for the modifier part?

```js
const obj = { hello: 'world' };

update(obj, { $set: { hello: 'mars' } });
```

Or is it already out there, and am I just missing all the fun?

**Comment by stalniy** [comment]
There are a lot of packages out there which supports different logic for setting values of complex objects. The simplest one is `lodash.get`

**Comment by smeijer** [comment]
I'm aware of the simple setter libraries. And they work fine, but not for more complex update operations. Also, the nice thing about having mongo syntax, is that we can use the same update operations to update the database, as wel as a local cache.

```js
const obj = {
  post: 'hello!',
  commenters: ['jack'],
};

update(obj, { $addToSet: { commenters: { $each: ['john', 'jane'] } } }
```

**Comment by crcn** [comment]
I think this kind of behavior would be better suited for a separate project. Sift is really just intended for filtering data.
