### ISSUE TITLE
Issues with Content Security Policy

### ISSUE THREAD

**Issue by kailashrdave** [crcn/sift.js#166]
We are using CASL for our project to check permissions.
recently we encountered that there are some issues with CSP in our application.
Going further, we found that it is because of sift.js which has something like following in javascsript...

`return"string"==typeof e?new Function("obj","return "+e)`

CASL uses "sift" for Mongo DB like filters in javascript.
I tried to go through CASL documentation, but found nothing related to CSP or Security.
Has anybody got this issue before? Is it possible to fix this without adding "unsafe-eval"

following is the code snippet from stif.js which causes problem

![stiff-js-error](https://user-images.githubusercontent.com/10292331/68774488-77b70700-062d-11ea-8841-36360f76dd59.png)

**Comment by stalniy** [comment]
@crcn Any thoughts?

**Comment by kailashrdave** [comment]
@crcn , @stalniy , could you please help to fix this issue.

**Comment by stalniy** [comment]
@crcn the simplest way to support this from your side is to provide CSP compliant version as a separate bundle e.g. `sift.csp.min.js`

**Comment by stalniy** [comment]
I can send a PR for this, otherwise I would be forced to publish a forked version...

**Comment by crcn** [comment]
> the simplest way to support this from your side is to provide CSP compliant version as a separate bundle e.g. sift.csp.min.js

great idea 👍. If you want to submit a PR I'd be happy to merge it in.

**Comment by crcn** [comment]
However, what are your thoughts around removing the eval code? That would obviously require a `major` version bump.

**Comment by stalniy** [comment]
You don’t need a major version bump. You will have just an additional file. So eventually there will be 2 files: sift.js and sift.csp.js

People will be able to use whatever file fits their needs. 

The plan is to add `if` statement with `process.env.CSP_ENABLED`. Using webpack or rollup (roll up is better to library development, less overhead in the bundle) I can inject this property and create 2 different files:
- one the same as now (sift.js) CSP_ENABLED = false
- and csp compliant version CSP_ENABLED = true

Uglifier can optimize this `if` (i.e. remove it)

**Comment by stalniy** [comment]
Are you ok to replace webpack with rollup? because I see that you started to integrate it :)

**Comment by stalniy** [comment]
No worries I will use webpack :)

**Comment by stalniy** [comment]
Done, now there is a new `sift.csp.min.js` file, which people can require using:
* `require('sift/sift.csp.min')`
* `import sift from 'sift/sift.csp.min'`

in order to use CSP compliant version, for the rest of the world everything remains the same, so this is a minor version update

**Comment by crcn** [comment]
Thanks @stalniy! Published to NPM as `9.0.1`. Lmk if your issue is fixed @kailashrdave.

**Comment by stalniy** [comment]
I missed one important thing... Webpack uses `window` as default global variable and for proper UMD build it should be `this`

**Comment by stalniy** [comment]
please check #170
