### ISSUE TITLE
$currentDate

### ISSUE THREAD

**Issue by djMax** [crcn/sift.js#167]
I would like to add $currentDate support to sift. I had hoped to do it with a custom expression, but I can't quite grok how to re-engage all the existing infrastructure for the "value" portion of the expression. i.e.

```
{ $currentDate: { $gte: new Date(whatever) } }
```

If $currentDate takes the source and the value, the value I assume is another sift doc running against just the currentDate? Is there a way to do that without hurting perf?

**Comment by crcn** [comment]
[Based on the docs I'm looking at](https://docs.mongodb.com/manual/reference/operator/update/currentDate/), I don't think `$currentDate` is compatible with Sift since it's an update operation. Sift only works with [query operations](https://docs.mongodb.com/manual/reference/operator/query/).
