### ISSUE TITLE
Support for $sort, $skip, $limit

### ISSUE THREAD

**Issue by p3t3r5** [crcn/sift.js#168]
It would be convenient to have this functionality

**Comment by stalniy** [comment]
Take a look at [mingo](https://github.com/kofrasa/mingo) it supports much more operators

**Comment by crcn** [comment]
> Take a look at mingo it supports much more operators

Agreed, I think `mingo` is what you're looking for @p3t3r5. Sift is really only intended for filtering, so operations like `$sort`, `$skip`, and `$limit` don't really fit.

**Comment by crcn** [comment]
Closing this ticket since these features aren't well suited for sift at the moment.
