### ISSUE TITLE
Issues with `sift/operations` module

### ISSUE THREAD

**Issue by stalniy** [crcn/sift.js#181]
`sift/operations` need to have own typescript typings otherwise I cannot use autocomplete in IDE and IDE shows an error, probably ts as well. See the error below:

![Screenshot from 2020-02-21 11-34-28](https://user-images.githubusercontent.com/1159966/75022287-7bfd8680-549e-11ea-9cac-d37c0f82b274.png)

**Comment by stalniy** [comment]
Actually there is no need for separate  `sift/operations` module, you can `export * from './operations'` inside index.js file, tree shaking can properly handle that.

Or do you have a specific reason to force users export operators from the separate module?

**Comment by stalniy** [comment]
Another issue with `sift/operations`, it uses ES6 module (i.e., `export * from "./es5m/operations"`), so it cannot be used in umd or commonjs builds. 

```sh
> require('sift/operations')
Thrown:
/home/sergii/projects/casl/packages/casl-ability/node_modules/sift/operations.js:1
export * from "./es5m/operations";
^^^^^^

SyntaxError: Unexpected token export
```

**Comment by stalniy** [comment]
Let me know whether you are OK to merge operations with sift and will create a PR.

**Comment by crcn** [comment]
yep, definitely okay with this change -- good suggestion. 👍🏻

**Comment by stalniy** [comment]
Done!
