### ISSUE TITLE
Changed behavior of $in: null 

### ISSUE THREAD

**Issue by marwej** [crcn/sift.js#184]
Another change in version 11 is handling of query `$in: null`. Before 11, the third test passed. I noticed that MongoDB does not accept `null` in the `$in` query either, so I guess that it's more correct now. It gives me some headache though. Would it be possible to accept `$in: null`?

```javascript
expect(sift({ $in: [1,2,3] })(1)).toBe(true);
expect(sift({ $in: [] })(1)).toBe(false);
expect(sift({ $in: null })(1)).toBe(false); // Does not work in MongoDB either
```

**Comment by crcn** [comment]
I'd prefer to keep as close as possible to Mongodb to prevent breakage for other libraries that use Sift. What are you trying to do exactly?

**Comment by marwej** [comment]
The array (and other parameters in the query) comes from a user generated variable. It might be null sometimes when still not initiated. This generates an error now, but was handled fine before. 

I guess I need to handle this in another way now.

**Comment by crcn** [comment]
One possible solution might be to transform the query coming in - what about something like this?

```javascript
const fixQuery = query => {
  const newQuery = {};
  for (const key in query) {
    let value = query[key];
    if (key === '$in' && value == null) {
      value = [];
    }
    newQuery[key] = value;
  }
  reutrn newQuery;
}
```

☝🏻might need some tweaking, but hopefully addresses the problem you're having.

Closing this ticket since there isn't anything I can do internally do the library, but feel free to open another ticket if you'd like help.
