### ISSUE TITLE
Ship ES6 version of the library 

### ISSUE THREAD

**Issue by stalniy** [crcn/sift.js#185]
Today there are major browsers support ES6 and ESM, so it make sense to ship ES6 version of your library together with commonjs and ES5M version.

Usually there are 3 types of versions which are good to have in your package:
- ES6 + ESM (ES modules)
- UMD - you have this
- ES5 + ESM (es5m or esm5) - you have this already

To make this job easier I'd recommend you to use rollup instead of webpack. The resulting bundle will be flat and smaller.

You can check https://github.com/stalniy/rollup-plugin-content/blob/master/rollup.config.js to see how I did this in one of my libraries.

Let me know if you need help with this, I can submit a PR.

**Comment by stalniy** [comment]
Did this for `minisearch` project. You can check that the package size is now noticeably smaller! 

https://bundlephobia.com/result?p=minisearch@2.1.4

**Comment by crcn** [comment]
Yeah, any help on this would be great! If you have a PR idea, I'd be happy to approve it.

**Comment by stalniy** [comment]
OK, the idea is to use Babel to transpile typescript into JS and use ts to emit types only. 

So, why Babel?
1. https://iamturns.com/typescript-babel/
2. You can use [@babel/preset-env](https://babeljs.io/docs/en/babel-preset-env) together with typescript and forget about polyfills!
3. You can use easier configuration with rollup to emit different bundles with simple configuration. 

I use this setup in casl. And pretty happy with that. 

There are obviously some nuances when you transpile typescript with Babel bit they are really minor. Especially if you combine this with the latest ts syntax for `export/import type`

**Comment by stalniy** [comment]
I already tried your repo with such configuration. It will require to either move some types into separate files or use `import/export type`
