### ISSUE TITLE
Second example for $exists is incorrect

### ISSUE THREAD

**Issue by abondoa** [crcn/sift.js#189]
There seems to be an mistake in the second example for the $exists:

```
//filtered: [{ name: 'Craig', city: 'Minneapolis' }]
[{ name: "Craig", city: "Minneapolis" }, { name: "Tim" }].filter(
  sift({ city: { $exists: false } })
);
```

At least when running the code (and also based on the mongo docs) the outcome is:

`[{ name: "Tim" }]`

I suggest to simply correct the example to the following:

```
//filtered: [{ name: "Tim" }]
[{ name: "Craig", city: "Minneapolis" }, { name: "Tim" }].filter(
  sift({ city: { $exists: false } })
);
```

I can create a PR for it if you prefer - I figure this is such a small thing to change that I wouldn't bother - let me know.

For reference, the exact code I have been running is this:

```
const sift = require( "sift");

console.log(
    [{ name: "Craig", city: "Minneapolis" }, { name: "Tim" }].filter(
        sift({ city: { $exists: false } })
    )
);
```

**Comment by crcn** [comment]
Thanks for catch! Yeah if you want to submit a PR, I'll go ahead and merge it. 👍🏻

**Comment by abondoa** [comment]
Here you go: https://github.com/crcn/sift.js/pull/190
