### ISSUE TITLE
$in differ from mongo

### ISSUE THREAD

**Issue by Eomm** [crcn/sift.js#196]
Hello,
I'm experiencing this issue with `sift@12.0.1` when performing and `$in` condition:

It seems that `['A', 'B']` match with the `[]` case.

```
const sift = require('sift')

const filter = {
  Demo: { $in: [null, [], 'C'] }
}

const fun = sift(filter)

console.log(fun({ Demo: ['A', 'B'] })) // should be false but it return true
console.log(fun({ Demo: null })) // true is ok
console.log(fun({ Demo: [] })) // true is ok
console.log(fun({ Demo: ['C'] })) // true is ok
```

I have tried it against Mongo 4.2.0 and the document doesn't match

**Comment by crcn** [comment]
Thanks for the catch! Fix has been published to NPM as `v13.0.2`.
