### ISSUE TITLE
RegExp global flag returns fewer results

### ISSUE THREAD

**Issue by dasantonym** [crcn/sift.js#200]
We have an app where people can create lists using their own regex filters. These filters run against an API using a MongoDB backend, but can also be exported to static files that are then queried using Sift, using the same queries.

Now I came across a RegExp using a 'g' flag that looks pretty much as in this Codepen here:
https://codepen.io/hyperfail/pen/bGVyaJG

The thing is, running against MongoDB the query returns all the items that match but with Sift I get a few items less. If I remove the 'g' flag Sift returns the same number.

Is this an expected behaviour? I wouldn't want to start modifying the users' expressions and at least MongoDB doesn't care about the flag.

**Comment by crcn** [comment]
Good catch! Looks like the problem was that Sift wasn't resetting the regular expression after testing each item. Fixed in `v13.0.5`.
