### ISSUE TITLE
Nested matching appears to be broken

### ISSUE THREAD

**Issue by redgeoff** [crcn/sift.js#206]
I just wanted to start by saying thanks again for a great lib!

I've been trying to upgrade the sift dependency for [mson](http://github.com/redgeoff/mson) from version sift 9.0.0. Unfortunately, I'm seeing a number of issues. I dug into a particular problem and am seeing an issue with matching nested queries, e.g. the following filter doesn't capture any values with sift v13.1.10. It does however work with sift v9.0.0:

```
import sift from "sift";

const where = {
  fields: {
    firstName: {
      value: {
        $eq: "Jimmy"
      }
    }
  }
};

const whereProps = {
  fields: {
    firstName: {
      value: "Jimmy"
    }
  }
};

const sifted = [whereProps].filter(sift(where));
console.log({ sifted });
```
Here's a [codesandbox for it not working in v13.1.10](https://codesandbox.io/s/sift13110-34qig). And one for it [working in v9.0.0](https://codesandbox.io/s/sift900-uxmzn)

I haven't had a chance yet to identify a root cause yet.

**Comment by crcn** [comment]
Glad you like it! `v12`-ish introduces a behavior change to better match MongoDBs functionality, so nested query searches like yours won't work anymore. Here's what you can do:

```javascript
const test = sift({
  "fields.firstName.value": {
    $eq: "Jimmy"
  }
})

test({
  fields: {
    firstName: {
      value: "Jimmy"
    }
  }
}); // true
```

Mongodb demo: https://mongoplayground.net/p/tPM8-xAb-4J
Code sandbox: https://codesandbox.io/s/sift13110-6gv4c

Let me know if you need anything else!

**Comment by redgeoff** [comment]
Interesting. Could you please elaborate on why we wouldn’t support both notations? (Perhaps this is more a question for MongoDB)

**Comment by crcn** [comment]
> Could you please elaborate on why we wouldn’t support both notations?

For _Sift_, the reasoning is that a lot of other Node modules that interact with MongoDB also use Sift, so it made sense to keep the functionality identical to ensure that all queries in Sift were also usable with MongoDB.

I don't know exactly why Mongo doesn't allow for nested queries, but my guess is that it's to create a boundary between the query language and data. For example, in MongoDB you can insert a document with a `$` operator like so:

```javascript
db.somestuff.insert(firstName: {
  value: {
    $eq: "Jimmy"
  }
});
```

And then query that:

```javascript
db.people.find({
  fields: {
    firstName: {
      value: {
        $eq: "Jimmy"
      }
    }
  }
});
```

Here's a demo: https://mongoplayground.net/p/jtnF2Z4es4S

**Comment by redgeoff** [comment]
I'm not sure I follow. Here's a [mongoplayground](https://mongoplayground.net/p/jtnF2Z4es4S) where you can filter by nested values in MongoDB, the exact filter that sift v13.1.0 does **not** support.

Configuration:
```
[
  {
    fields: {
      firstName: {
        value: {
          $eq: "Jimmy"
        }
      }
    }
  }
]
```

Query:
```
db.collection.find({
  fields: {
    firstName: {
      value: {
        $eq: "Jimmy"
      }
    }
  }
})
```

**Comment by crcn** [comment]
☝🏻 MongoDB in this case is treating `$eq` has a prop. Here's a better example: https://mongoplayground.net/p/0UIcUQl8Z3v

**Comment by redgeoff** [comment]
OK, I think I follow now. Here you can see that the [nesting does not work](https://mongoplayground.net/p/tPM8-xAb-4J), but the [dot notation does work](https://mongoplayground.net/p/2APTi646eLO)
