### ISSUE TITLE
null equality bug

### ISSUE THREAD

**Issue by sakulstra** [crcn/sift.js#208]
We're using sift to unit-test some query builder for mongodb and noticed some discrepancy between sift and mongodb.
I'm actually not quite sure if that is a mongodb or sift bug :sweat_smile: at least it's inconsistency between the both.
Reading the mongodb docs, i would actually assume that the sift behavior is correct: https://docs.mongodb.com/manual/tutorial/query-for-null-fields/#equality-filter making this whole issue kinda weird

### Testcase
```
const input = {
  field: []
};

const filter = {
  "field.0": null
};

const sifted = [input].filter(sift(filter));
```
https://codesandbox.io/s/sift13110-5svxi?file=/src/index.js

### outcome
- Sift returns the input element
- Mongodb doesn't

**Comment by crcn** [comment]
Thanks for catching this, and sorry for the slow response! 🙈

Fixed & published to NPM as `v13.3.0`.
