### ISSUE TITLE
$elemMatch and $size on the same field does not work

### ISSUE THREAD

**Issue by jhmajjh** [crcn/sift.js#214]
Hi Craig,

Thanks a lot for the fix! The problem with the different behaviour when calling sift once as opposed to calling in multiple times is gone. I still got some strange behaviour when calling `$elemMatch` and `$size` at the same time in **sift 13.3.5**. Say, I have two objects, each with an array of embedded objects, the first one has one object inside the array, the second one has two:

```
const sift = require('sift')

const values = [
  {
    name: 'oneElement',
    myArray: [
      { firstKey: 'a', secondKey: 'b' }
    ]
  },

  {
    name: 'twoElements',
    myArray: [
      { firstKey: 'a', secondKey: 'b' },
      { firstKey: 'c', secondKey: 'd' }
    ]
  }
]
```
If I want to get the value where `myArray` has only `{ firstKey: 'a', secondKey: 'b' }`, and nothing else, I'd run a query like this in MongoDB:

```
const query = {
  myArray: {
    $elemMatch: { firstKey: 'a', secondKey: 'b' },
    $size: 1
  }
}

console.log('query:', values.filter(sift(query)))
```

Expected behaviour: `query` should return `oneElement`.
Actual behaviour: `query` returns an empty array.

Maybe it’s a general thing when applying two operators on the same field?

Best wishes and thank you for your work!

Christopher

**Comment by crcn** [comment]
Should be fixed & published to NPM as `13.4.0`. Thanks for catching this!
