### ISSUE TITLE
Nested object equality with filter with fewer keys than array objects

### ISSUE THREAD

**Issue by eric-swann-q2** [crcn/sift.js#216]
Hello, based on the tests in this project, I would expect the following test to succeed:

```
it('should find an auth by nested object criteria', async () => {
    const auths = [
      { disabled: false, prop1: { name: 'myTestBiller1', prop2: 'prop2' } },
      { disabled: true, prop1: { name: 'myTestBiller2', prop2: 'prop2' } },
    ]

    const foundAuths = auths.filter(
      sift({
        prop1: { name: 'myTestBiller1' },
      })
    )

    expect(foundAuths).toHaveLength(1)
  })
```
It doesn't work because when passing a nested object as the filter, it is expecting the keycount on the filter to equal the keycount on the object it is filtering. So in this case it fails because the nested filter only has a 'name' key and the object it's filtering has two keys: name and prop2. Is this the expected behavior?

It's due to these lines in src/utils.ts:
```
 if (Object.keys(a).length !== Object.keys(b).length) {
                return false;
            }
```

If I use a segmented filter, such as `"prop1.name":"myTestBiller1"`, it works as expected.

**Comment by crcn** [comment]
This is actually intended behavior since MongoDB acts this way. For example:

```javascript
it('should find an auth by nested object criteria', async () => {
    const auths = [
      { disabled: false, prop1: { name: 'myTestBiller1', prop2: 'prop2' } },
      { disabled: true, prop1: { name: 'myTestBiller2', prop2: 'prop2' } },
    ]

    const foundAuths = auths.filter(
      sift({
        prop1: { name: 'myTestBiller1' },
      })
    )

    expect(foundAuths).toHaveLength(1)
  })

````

In Mongodb returns an empty result: https://mongoplayground.net/p/mDZ9kKK47Nk
