### ISSUE TITLE
Support MongoDB type aliases

### ISSUE THREAD

**Issue by marwej** [crcn/sift.js#218]
Would it be possible to support the type aliases when using the `$type` operator? I store/transfer configuration, including queries used with sift, as JSON documents so the queries need to be valid JSON. Most important is to support `{$type: "number"}`.

https://github.com/crcn/sift.js/blob/master/src/operations.ts#L285
https://docs.mongodb.com/manual/reference/operator/query/type/#document-type-available-types

**Comment by crcn** [comment]
Yep, great idea. I'll get it done here in a bit!
