### ISSUE TITLE
In dependency scan, nested dependency handlebars is vulnerable issue occurs due to lower version

### ISSUE THREAD

**Issue by deepiga-obs** [crcn/sift.js#222]
In Azure pipelines, perform security scan is failed due to nested dependency handlebars@^4.0.1

While doing dependency scan in deployment pipelines or run the following command in the local environment
`docker run --rm -e "WORKSPACE=%cd%" -v %cd%:/app shiftleft/sast-scan scan --build`
the issue occurs as shown below

![dep_scan](https://user-images.githubusercontent.com/69249205/115257678-ef0b9700-a14d-11eb-8284-6351456bdff6.jpg)

**Steps to reproduce**,
1. Create a new empty node js project
2. install mongoose package
3. Check the node_modules folder, it contains sift package. Inside the sift package we can found yarn lock file with handlebars@^4.0.1

**Comment by crcn** [comment]
Security issues have been fixed. Let me know if you're still dealing with this issue!
