### ISSUE TITLE
Cannot find name 'TimerHandler' in operations.d.ts

### ISSUE THREAD

**Issue by NicoBeyer** [crcn/sift.js#223]
Since version 13.5.2 I get the following Typecript error:

node_modules/sift/lib/operations.d.ts:64:37 - error TS2304: Cannot find name 'TimerHandler'.

64 export declare const $type: (clazz: TimerHandler, owneryQuery: any, options: Options) => EqualsOperation<(b: any) => any>;

**Comment by crcn** [comment]
Oh weird, this shouldn't have happened. `$type` uses `Function | string`, not `TimerHandler`. Looks like tsc converts unions into core library types if it can find one?

I'll fix this here in a sec.

**Comment by crcn** [comment]
Should be fixed now in `v13.5.3`. Let me know if you have anymore issues!
