### ISSUE TITLE
$nor functionality is not working properly

### ISSUE THREAD

**Issue by 3oudi** [crcn/sift.js#225]
i faced unusual behavior in the $nor functionality while using it in my application. So to make sure i took the example existent in the documentation , and like expected the result is different.

the documentation example :

`//filtered: [ { name: 'Tim', state: 'MN' }, { name: 'Joe', state: 'CA' }]
[
  { name: "Craig", state: "MN" },
  { name: "Tim", state: "MN" },
  { name: "Joe", state: "CA" }
].filter(sift({ $nor: [{ name: "Craig" }, { state: "MN" }] }));`

executing the above in nodejs :
`//filtered [ { name: 'Joe', state: 'CA' } ]
[
        { name: "Craig", state: "MN" },
        { name: "Tim", state: "MN" },
        { name: "Joe", state: "CA" }
      ].filter(sift({ $nor: [{ name: "Craig" }, { state: "MN" }] }));`
      
Could you please explain? am i wrong ? i really get confused.
Thank you

**Comment by 3oudi** [comment]
The above issue wasn't in the code. the example existining in the documenation is wrong.

shoud be like this :

[
        { name: "Craig", state: "MN" },
        { name: "Tim", state: "MN" },
        { name: "Joe", state: "CA" }
      ].filter(sift({ $nor: [{ name: "Craig",state: "MN"  }] }));
      
  thank you

**Comment by crcn** [comment]
You're right! Thanks for catching that.
