### ISSUE TITLE
Different behavior of $or: [] vs $and: []

### ISSUE THREAD

**Issue by j2L4e** [crcn/sift.js#236]
I noticed that `$and: []` always evaluates to true, yet `$or: []` always evaluates to false. 
Personally, I'd expect both to always return true or at least behave in the same way.

Is this intended behavior?

https://codesandbox.io/s/modest-babycat-99f7f?file=/src/index.js

**Comment by crcn** [comment]
Should be be throwing a `malformed query` error:


<img width="1904" alt="Screen Shot 2021-09-24 at 9 17 47 AM" src="https://user-images.githubusercontent.com/757408/134689848-91146a1d-4990-4de0-9bdf-4b5bd020f217.png">


Added a fix and published to NPM as `v15.0.0`. Let me know if there's anything else!

**Comment by j2L4e** [comment]
Thanks!
