### ISSUE TITLE
Throw on unknown operator

### ISSUE THREAD

**Issue by marwej** [crcn/sift.js#239]
After upgrading to 14+ sift.js no longer throws on unknown operator. This does not pass:

```javascript
it("should throw on unknown operator", () => 
  expect(() => sift({ a: { $fooBar: 42 } })({})).toThrow());
```

MongoDB throws an error.

![image](https://user-images.githubusercontent.com/5296840/143771921-da4b5bac-2d36-4831-a601-6afc91ee229e.png)

**Comment by crcn** [comment]
Should be fixed in `v15.1.0`. Let me know if you have anymore issues!
