### ISSUE TITLE
Implicit AND operation

### ISSUE THREAD

**Issue by curvedriver** [crcn/sift.js#243]
Hi,
MongoDB supports implicit `AND` operations which simplifies a query.

Is it on purpose that such a implicit `AND` operation doesn't work?

Quote: 
https://docs.mongodb.com/manual/reference/operator/query/and/#and-queries-with-multiple-expressions-specifying-the-same-field

### Expected behaviour:
https://mongoplayground.net/p/YWgjr-PM6z5

### Example 
The following example returns an empty array at version `15.1.3`

``` javascript
// 
const result = [{
    tags: [
        'animal',
        'dog'
    ]
}, {
    tags: [
        'animal',
        'cat'
    ]
}, {
    tags: [
        'animal',
        'mouse'
    ]
}].filter(sift({
    tags: {
        $in: [
            'animal'
        ],
        $nin: [
            'mouse'
        ]
    }
})); // []
```

**Comment by crcn** [comment]
Should be fixed in v16.0.0!
