### ISSUE TITLE
Feature Request: Export other query types like `ShapeQuery`

### ISSUE THREAD

**Issue by Helveg** [crcn/sift.js#250]
Hi! Pretty simple feature, I want to have access to the `ShapeQuery` because I'll apply `sift` only to objects and I would like to have stricter type safety to the inputs that will be given to `sift`.

By extension, I suppose it would be useful to export the other constituent types as well such as `BasicValueQuery` for a `keyof BasicValueQuery` etc! Since it's just slapping `export` on a few `type`s, I can PR this! 😂

**Comment by crcn** [comment]
>  I can PR this

That would be awesome 🙏 . Feel free to do that and I'll merge it in!
