### ISSUE TITLE
Support field names containing dots

### ISSUE THREAD

**Issue by kpapadatos** [crcn/sift.js#261]
Consider the following two documents:
```
A: { foo: { bar: 2 } }
B: { 'foo.bar': 2 }
```

The query below matches only document A, but would also match document B if it ran against a MongoDB collection:
```ts
const isMatch = sift({ 'foo.bar': 2 });

isMatch({ foo: { bar: 2 } }); // true
isMatch({ 'foo.bar': 2 });    // false
```

**Comment by crcn** [comment]
I'm unable to get MongoDB to behave here: https://mongoplayground.net/p/eiTJyGJPzfH.

Anything I'm missing?

**Comment by kpapadatos** [comment]
@crcn Apologies, I can't reproduce this anymore. I either made a mistake or my client lib was doing something shady with https://www.mongodb.com/docs/manual/reference/operator/aggregation/getField/#mongodb-expression-exp.-getField under the hood.
