### ISSUE TITLE
Where are the release entries for versions 17 and 14?

### ISSUE THREAD

**Issue by hasezoey** [crcn/sift.js#262]
From my quick glance, there is [changelog.md](https://github.com/crcn/sift.js/blob/master/changelog.md) but it does not list version 14 and 17, and looking at [releases](https://github.com/crcn/sift.js/releases) there only seems to be one for 15 (and releases does not even list the changes)

**Comment by crcn** [comment]
Thanks for pointing this out, the changelog.md should be updated now!
