### ISSUE TITLE
implement aggregation framework

### ISSUE THREAD

**Issue by jochenonline** [crcn/sift.js#35]
Has anyone yet or are there any plans to integrate the functionality of the mongodb aggregation framework?

**Comment by WAKlNYAN** [comment]
@jochenonline Interesting, but it doesn't run. What is this `mapObject()` method you're using? Where does it come from?

@crcn with all due respect, I am at a loss as to why you wouldn't be adopting the aggregation functionality into sift. How is the fiddle.js repository you cited relevant to this conversation?

**Comment by jochenonline** [comment]
Maybe this was part of an older version of sift. As you can see my code is from 2014.

**Comment by crcn** [comment]
The reason why the aggregation framework didn't seem to fit was because Sift is a filtering library, and I didn't want responsibilities to extend beyond that. Since 2014 the library has become more focused.
