### ISSUE TITLE
Sorting problem

### ISSUE THREAD

**Issue by goloroden** [crcn/sift.js#40]
We ran sift.js with the following code:

```
var sift = require('sift');
console.log(sift({}, [ 23, 42 ]));
```

The expected output is:

```
[ 23, 42 ]
```

The actual output is:

```
[ 42, 23 ]
```

We tracked this down to [the following lines](https://github.com/crcn/sift.js/blob/87026295781f0736a30e38e81742917ffdb46235/sift.js#L472-L475). If you comment them out, everything works as expected, but probably there's some meaning behind their existence ;-)

So, the question is how to deal with this issue properly? Any hints?

We would be happy to provide a pull request (e.g. to make sorting optional), but we wanted to make sure first that we are doing the right thing, before doing things right ;-))

**Comment by Redsandro** [comment]
@crcn The new version seems to work fine. :+1: 

Is the logic that caused the original issue clear? Can you elaborate a bit on that for me?

I'm wondering if I should lock my `package.json` to use a specific version that I know to work (`0.2.3`), or if it's fairly certain that this won't happen again when trying to solve the issue that caused the original regression; i.e. I can rely on silent updates; e.g. `~0.2`.

**Comment by crcn** [comment]
The original implementation was created on the idea that MongoDB automatically sorts results based on a search query. However, that doesn't seem to be the case, so I wouldn't expect this to be an issue again in any future version of sift.js.
