### ISSUE TITLE
Allow module to be extended or support for custom filters

### ISSUE THREAD

**Issue by Redsandro** [crcn/sift.js#45]
Quote from PR [here](https://github.com/crcn/sift.js/pull/43#issuecomment-62194895):

> Does this module provide a way to override a function like `$regex()` so I can
keep sift as a dependency instead of forking it?

As far as I know, the anonymous functions make the scope of those functions private. I would have to be able to access `sift.<function scope>._queryParser.parse.<function scope>._testers.$regex` in order to override this.

Is there another way to extend tester functions? If not, a feature request would be some sift-native way to load custom tester functions

**Comment by crcn** [comment]
`0.2.x` fixes the sorting problem - you should be able to use custom expressions now!
