### ISSUE TITLE
Why leak of $elemMatch?

### ISSUE THREAD

**Issue by chengxuntao** [crcn/sift.js#57]
Is there any reason for this?
There's a similar project [qry](https://github.com/manuelstofer/qry/blob/master/index.js), it include an $elemMatch implementation.

**Comment by crcn** [comment]
SiftJS makes `$elemMatch` a little redundant since you can achieve the same thing with deep object searching, like so:

```javascript
var people = [{
  name: 'craig',
  address: {
    city: 'Minneapolis'
  }
},
{
  name: 'tim',
  address: {
    city: 'St. Paul'
  }
}];

var sifted = sift({ address: { city: 'Minneapolis' }}, people); // count = 1

//or
var sifted = sift({'address.city': 'Minneapolis'}, people);//count = 1
```

These too: https://github.com/crcn/sift.js/blob/master/test/objects-test.js

`$elemMatch` *could* be implemented, but that would only be to make SiftJS more true to the MongoDB.
