### ISSUE TITLE
elemMatch

### ISSUE THREAD

**Issue by wiiny** [crcn/sift.js#58]
Hi, I have some troubles to use elemMatch. Here is my array (or collection mongodb) : 
var couples = [{
                  name: "SMITH",
                  person: [
                      {
                          firstName: "craig",
                          gender: "female",
                          age: 29
                      },
                      {
                          firstName: "tim",
                          gender: "male",
                          age: 32
                      }

                  ]
              },
              {
                  name: "JOHNSON",
                  person: [
                      {
                          firstName: "emily",
                          gender: "female",
                          age: 35
                      },
                      {
                          firstName: "jacob",
                          gender: "male",
                          age: 32
                      }

                  ]
              }];

I have two tests : 
sift({"person.gender": "female", "person.age": {"$lt": 30}}, couples) => ok 1 result but a chance
sift({"person.gender": "male", "person.age": {"$lt": 30}}, couples); => KO

The mongodb commands are : 
db.couples.find({"person": {"$elemMatch":{"gender": "female", "age": {"$lt": 30}}}}) => OK 1 result
db.couples.find({"person": {"$elemMatch":{"gender": "male", "age": {"$lt": 30}}}}) => OK no result

Can you add $elemMatch in sift ?

Thanks

**Comment by crcn** [comment]
Done! `$elemMatch` has been added to `1.1.0`.

**Comment by wiiny** [comment]
Hi ! Thanks for your reactivity. But I still have trouble : 
sift({"person": {"$elemMatch": {"gender": "female", "age": {"$lt": 30}}}}, couples)
=> OK 1 result
sift({"person": {"$elemMatch": {"gender": "male", "age": {"$lt": 30}}}}, couples)
=> KO 1 result, should have 0 result

Furthemore, I tried 2 combined elemMatch (with a $and) and the result is wrong : 
sift({"$and": [{"person":{"$elemMatch":{"gender": "male", "age": {"$gte": 32}}}},
                                  {"person":{"$elemMatch":{"gender": "female", "age": {"$gt": 30}}}}]}, couples)
=> KO 2 results, should have 1 result

**Comment by crcn** [comment]
Hmm - seems like `$elemMatch` has introduced a new bug that requires some refactoring. Should be fixed here in a little bit.

**Comment by ohmance** [comment]
+1 this is a very useful operator for what I'm implementing.

**Comment by crcn** [comment]
Currently working on this
