### ISSUE TITLE
Issue with value 0 in $in operator

### ISSUE THREAD

**Issue by roshan-built-io** [crcn/sift.js#60]
I have sample code over here on which I am trying "$in" operator to search value 0, but not getting expected result.

data = [{"a":{"b":[{"status":0}]}},{"a":{"b":[{"status":2}]}}]

Query : 
objects = sift({"a.b.status":{"$in": [0, 2]}}, data);
//result = 1, expected result = 2

objects = sift({"a.b.status":{"$in": [0]}}, data);
//result = 0, expected result = 1

objects = sift({"a.b.status":{"$in": [2]}}, data);
//result = 1, expected result = 1

Could you please help?

**Comment by crcn** [comment]
Should be fixed with `2.x`.
