### ISSUE TITLE
Consider mongodb style updates.

### ISSUE THREAD

**Issue by DylanPiercey** [crcn/sift.js#63]
I found this project:
https://github.com/Automattic/mongo-query

And was wondering if there were any plans to add mutating operators to this lib? It would be pretty handy to have to full functionality of mongodb queries in the browser.

**Comment by crcn** [comment]
The intended purpose of this library is to filter arrays using mongodb queries. I think if anything it'd be appropriate to create another repo for this sorta of feature. That way you can opt-in or out of it without the additional bloat. For example:

```javascript
var people = [{ age: 100 }, { age: 50 }, { age: 20 }];
update(sift({ age: { $gt: 20 }}), { $inc: { age: 1 }});
```

**Comment by smeijer** [comment]
About that code sample, that's not always going to work:

```js
update(sift({ 'nested.age': { $gt: 20 }}), { $inc: { 'nested.$.age': 1 }});
```
