### ISSUE TITLE
Website looks like it's down

### ISSUE THREAD

**Issue by nickell** [crcn/sift.js#65]
I just wanted to bring it to your attention that I'm getting a HTTP Error 403.14 - Forbidden when I navigate to [siftjs](http://siftjs.com/).

**Comment by crcn** [comment]
Thanks for the heads up. Updated the DNS config so the site should be up in a few days or so.

**Comment by nickell** [comment]
Awesome, that was a quick response. I just started using this today and it is fantastic, thanks for making an excellent tool!

**Comment by crcn** [comment]
Awesome, glad you like it!

**Comment by fusepilot** [comment]
It's currently down.
