### ISSUE TITLE
Array $gt/$lt comparisons not passing

### ISSUE THREAD

**Issue by ohmance** [crcn/sift.js#70]
In this code:
`sift({groups:{$gt:5}}, [{groups:[1,2,3,4]}, {groups:[7,8]}])`
An empty array is returned.  Based on how MongoDB functions I expect to receive:
`[{groups:[7,8]}]`

**Comment by ohmance** [comment]
This same behavior seems to also occur in the $mod operator.

**Comment by crcn** [comment]
Fixed - thanks!
