### ISSUE TITLE
Cross browser differences

### ISSUE THREAD

**Issue by ohmance** [crcn/sift.js#75]
The following query performs different across browsers:
`sift({}, [{myobj:1}])`

Chrome (v44) returns [{myobj:1}]
Safari (v8.0.5 as well as iOS 8) returns []
Firefox (31.0) returns []

Chrome performs the way I would expect since find({}) in mongo returns all documents.

**Comment by ohmance** [comment]
FWIW, the same behavior is demonstrated with this query:
`sift({$and:[]}, [{myobj:1}])`

Mongo excepts with such a query, not that Sift should.

**Comment by ohmance** [comment]
Somewhat naive of me, this issue seems more serious.  Every function I attempt with sift in both Safari and Firefox fails.  Really hope this isn't some boneheaded thing I'm doing.

Example:
`sift({'first_name':'ben'}, [{first_name:'ben'}])`
Returns [] in FF and Safari
Returns [{first_name:'ben'}] in Chrome

I'll start looking into why this is.  Hints are welcome.

**Comment by crcn** [comment]
This is likely an issue with conditional logic where behavior might vary across different platforms. I'm guessing the problem lies in one of these places:

https://github.com/crcn/sift.js/blob/master/sift.js#L32
https://github.com/crcn/sift.js/blob/master/sift.js#L385

In any case, sounds like I need to setup the automated tests with [BrowserStack](http://browserstack.com/), or [testling](https://ci.testling.com/) to prevent this sort of thing from happening again the future. Thanks for catching this!

**Comment by ohmance** [comment]
I think that's exactly what's going on.  When I comment out https://github.com/crcn/sift.js/blob/master/sift.js#L387 it works fine in FF.  The comparison object.constructor.toString() !== "function Object() { [native code] }" succeeds in FF because object.constructor.toString() actually is slightly different:

`"function Object() {
    [native code]
}"`

In Safari it's this:
"function Object() {
    [native code]
}"

Adding this string into the logic gets it to work for FF, but Safari is failing a little deeper and seems to be experiencing infinite recursion.

**Comment by crcn** [comment]
Eeesh - yeah. Sounds like the Safari issue is stemming from somewhere around `line 387`. I'll take at a fix here in a bit with [karma](http://karma-runner.github.io/0.13/index.html) tests.

**Comment by ohmance** [comment]
I'm having trouble reproducing the recursion issue I had before.  Merely changing lines 385-388 to what's below seems to be working in both FF and Safari:

```javascript
if (!query || (query.constructor.toString() !== "Object" &&
     query.constructor.toString().replace(/\n/g,'').replace(/ /g, '') !== "functionObject(){[nativecode]}")) {
   query = { $eq: query };
}
```

**Comment by ohmance** [comment]
I've deployed this on a few hundred iPads the past couple days with the above mentioned change (lines 385-388) and it seems to be working fine in Safari.  Tests in Firefox have succeeded as well.  Would be nice to get this added to bower so things are clean.  I'm happy to make a PR with this fix if you aren't already working on some other things.

**Comment by crcn** [comment]
This is awesome - thanks for all the investigating! A PR would be great if you can quickly do that. Got my hands tied up with other stuff at the moment. 

- Craig
