### ISSUE TITLE
validator for empty array

### ISSUE THREAD

**Issue by johnwillyn** [crcn/sift.js#82]
I ran into a case that sift does not handle like Mongo which I realize might be obscure, but I thought I would report it.

I have an array of (string) status items like so: status: ["urgent", "completed", "today"], and quite often after some user manipulation, the status array can be empty (=== []) (but you can't test for empty array equivalence directly in javascript).

My filter tests for this as one of the $or: cases: 
```javascript
statusQuery = {$or: [{status: {$exists: false}},
                             {status: []},
                             {status: {$in: $scope.statusFilter.statusFilters}}
                            ]};
```
I know I could do this with a $size operator, but I tested this in the Mongo shell, and it does work and detects the empty array equivalence as written above.

I found a way to fix it in my local build, so I am passing it along in case this is useful.

In the prepare.$eq function I added a special case for the empty array:
```javascript
  $eq: function(a) {

      if (a instanceof RegExp) {
        return function(b) {
          return typeof b === "string" && a.test(b);
        };
      } else if (a instanceof Function) {
        return a;
      } else if (isArray(a) && !a.length) {
        // Special case of a == []
        return function(b) {
          return (isArray(b) && !b.length)
        }
      }

      return function(b) {
        return a === comparable(b);
      };
    },
```
And then in the or validator, I added a check for a zero length array:
```javascript
  function or(validator) {

    return function(a, b) {
      // Treat empty array as normal validator call
      if (!isArray(b) || !b.length) return validator(a, b);
      for (var i = 0, n = b.length; i < n; i++) if (validator(a, b[i])) return true;
      return false;
    }
  }
```
I added this to the and validator case as well.

I am not sure if the goal is to match Mongo for these types of cases, but thought it might be a useful case for others.

I made one other change to my local version.  I changed isArray to use a polyfill for Array.isArray().  It seems to speed the compares up, but I have not done any benchmarks yet.

Thanks for the great little query/filter library!

**Comment by crcn** [comment]
Definitely trying to match how Mongodb works, so this is definitely a bug. I'll take a look at this once I'm back from vacation. Thanks for pointing this out!
