### ISSUE TITLE
extending to aggregation

### ISSUE THREAD

**Issue by johnwillyn** [crcn/sift.js#85]
This is not an issue, but an exploration.

I have been gaining a working understanding of the sift.js framework, and it seems like it might be fairly straightforward to adapt this same (expression) framework for emulating other parts of the Mongo aggregation framework.  I am most interested in the $group operations and expressions for now, and was wondering how far off I might be on this.

Any feedback is appreciated.  I would certainly be interested in collaborating on such a project.

**Comment by crcn** [comment]
This definitely seems useful, and it lines up a bit with another project I'm working on: [mesh](http://mesh.js.org). 

I'd love to work on this sort of thing, but right now I'm hosed with other stuff. Great idea though!

- Craig

**Comment by johnwillyn** [comment]
Thanks for passing along the link to mesh!  Seems very useful for structuring interfaces and API in my current project as well.  I like the simplicity and embedding bus concept.

I have a good start on the aggregate lib, and hope to post after I do some cleanup and add a few more operations.

BTW, I notice you are using a lot of ES6 (and a little ES7) in your mesh examples.  What toolset (or polyfills) are you using for these?

**Comment by crcn** [comment]
I'm using [babel](https://babeljs.io/) right now for other projects, but any other toolset should working so long as it has promises.
