### ISSUE TITLE
Dot notation for arrays not supported

### ISSUE THREAD

**Issue by erwinw** [crcn/sift.js#90]
In [Mongo](https://docs.mongodb.org/manual/core/document/#dot-notation) you can use dot notation both to compare object fields _and array elements_, but this unfortunately doesn't seem to work in sift:

      sift({'foo.0':42}, [{foo: [42]}] );

returns `[]`, not the expected `{foo: [42]}`. This makes matching individual array items really hard (impossible?)

**Comment by readme42** [comment]
:+1:

**Comment by jochenonline** [comment]
:+1:
