### ISSUE TITLE
$regex behaviour not like mongo

### ISSUE THREAD

**Issue by matusszabo** [crcn/sift.js#99]
Hi, sift is fantastic lib, just wondering why $regex not matching string array as mongodb:
var match = { folder: { $regex:'^[0-9]{4}$' }};
var array = [{ folder:['1234','3212'] }];
console.log( sift(match, array) ); // result = [], mongodb will match it, because of min. one element is matched regex query, even if there will be more elements with non numeric values

var array = [{ folder:['3212'] }];
console.log( sift(match, array) ); // result = [{ folder:['3212'] }], correct mongodb behaviour

thank you

**Comment by crcn** [comment]
Hmm - doesn't seem like I'm able to reproduce this. Here's what I have:  https://jsfiddle.net/5c0sqajn/

Do you have a runnable example where this is breaking?

**Comment by matusszabo** [comment]
You are right, it was old version installed by npm, sorry.
